<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5198" started-at="2016-11-07T04:40:18Z" finished-at="2016-11-07T04:40:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5198" started-at="2016-11-07T04:40:18Z" finished-at="2016-11-07T04:40:23Z">
      <class name="utilities.testjjdsfjg">
        <test-method status="FAIL" signature="hello()[pri:0, instance:utilities.testjjdsfjg@815b41f]" name="hello" is-config="true" duration-ms="0" started-at="2016-11-07T10:10:18Z" finished-at="2016-11-07T10:10:18Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at frameworkGlobals.ByID.click(ByID.java:15)
	at utilities.testjjdsfjg.hello(testjjdsfjg.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hello -->
        <test-method status="SKIP" signature="hello2()[pri:0, instance:utilities.testjjdsfjg@815b41f]" name="hello2" duration-ms="2" started-at="2016-11-07T10:10:23Z" finished-at="2016-11-07T10:10:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hello2 -->
      </class> <!-- utilities.testjjdsfjg -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
